networks:
  system:
    name: system

services:
  mysql:
    image: mysql:8.3
    container_name: mysql
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQ_DEFAULT_AUTHENTICATION_PLUGIN: mysql_native_password
    networks:
      system:
        aliases:
          - mysql
